import path from "node:path";
import { defineConfig } from "vitest/config";

const projectRoot = path.resolve(import.meta.dirname, "../..");

export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: [
      path.join(projectRoot, "tests/setup/env.ts"),
      path.join(projectRoot, "tests/setup/frontend.ts"),
    ],
    include: [
      "tests/unit/frontend/app-topbar-accessibility.test.ts",
      "tests/unit/frontend/auth-form-controller-characterization.test.ts",
      "tests/unit/frontend/auth-form-presentation.test.ts",
      "tests/unit/frontend/auth-form-transitions.test.ts",
      "tests/unit/frontend/browser-integration-transitions.test.ts",
      "tests/unit/frontend/chatwoot-client.test.ts",
      "tests/unit/frontend/chatwoot-decomposition.test.ts",
      "tests/unit/frontend/chatwoot-widget.test.ts",
      "tests/unit/frontend/critical-flow-components.test.ts",
      "tests/unit/frontend/install-app-button.test.ts",
      "tests/unit/frontend/install-app-button-state.test.ts",
      "tests/unit/frontend/install-app-controller-characterization.test.ts",
      "tests/unit/frontend/layout-mobile-focus.test.ts",
      "tests/unit/frontend/link-account-edge-semantics.test.ts",
      "tests/unit/frontend/link-account-presentation.test.ts",
      "tests/unit/frontend/link-account-transitions.test.ts",
      "tests/unit/frontend/page-shell-accessibility.test.ts",
      "tests/unit/frontend/payment-controller-characterization.test.ts",
      "tests/unit/frontend/payment-presentation.test.ts",
      "tests/unit/frontend/payment-return-controller-characterization.test.ts",
      "tests/unit/frontend/payment-return-status-component.test.ts",
      "tests/unit/frontend/payment-return-status-state.test.ts",
      "tests/unit/frontend/passkey-controller-characterization.test.ts",
      "tests/unit/frontend/passkey-presentation.test.ts",
      "tests/unit/frontend/profile-controller-characterization.test.ts",
      "tests/unit/frontend/profile-email-change-feedback.test.ts",
      "tests/unit/frontend/profile-presentation.test.ts",
      "tests/unit/frontend/profile-transitions.test.ts",
      "tests/unit/frontend/referral-program-controller-characterization.test.ts",
      "tests/unit/frontend/referral-program-panel.test.ts",
      "tests/unit/frontend/referral-program-presentation.test.ts",
      "tests/unit/frontend/register-email-confirm-controller-characterization.test.ts",
      "tests/unit/frontend/register-email-confirm-transitions.test.ts",
      "tests/unit/frontend/telegram-webapp-login-controller.test.ts",
      "tests/unit/frontend/telegram-webapp-login-lifecycle.test.ts",
      "tests/unit/frontend/telegram-webapp.test.ts",
      "tests/unit/frontend/verify-email-state.test.ts",
      "tests/unit/frontend/verify-email-controller.test.tsx",
    ],
    pool: "forks",
    testTimeout: 15_000,
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      reportsDirectory: "coverage/frontend",
      include: [
        "src/frontend/layout/AppTopbar.tsx",
        "src/frontend/layout/layout.tsx",
        "src/frontend/components/auth-shell.tsx",
        "src/frontend/components/auth-form-transitions.ts",
        "src/frontend/components/link-account-panel.tsx",
        "src/frontend/components/link-account-presentation.ts",
        "src/frontend/components/link-account-transitions.ts",
        "src/frontend/components/chatwoot-widget.tsx",
        "src/frontend/components/chatwoot-widget-controller.ts",
        "src/frontend/components/chatwoot-widget-state.ts",
        "src/frontend/components/extend-confirmation.tsx",
        "src/frontend/components/extend-confirmation-presentation.ts",
        "src/frontend/components/install-app-button.tsx",
        "src/frontend/components/install-app-button-state.ts",
        "src/frontend/components/passkey-actions.tsx",
        "src/frontend/components/passkey-presentation.ts",
        "src/frontend/components/payment-confirmation.tsx",
        "src/frontend/components/payment-confirmation-presentation.ts",
        "src/frontend/components/payment-return-status.tsx",
        "src/frontend/components/payment-return-status-state.ts",
        "src/frontend/components/profile-panel.tsx",
        "src/frontend/components/profile-presentation.ts",
        "src/frontend/components/profile-transitions.ts",
        "src/frontend/components/referral-program-panel.tsx",
        "src/frontend/components/referral-program-presentation.ts",
        "src/frontend/components/register-email-confirm-form.tsx",
        "src/frontend/components/register-email-confirm-transitions.ts",
        "src/frontend/components/telegram-webapp-login.tsx",
        "src/frontend/components/verify-email-panel.tsx",
        "src/frontend/components/verify-email-state.ts",
        "src/frontend/hooks/use-link-account-controller.ts",
        "src/frontend/hooks/use-auth-form-controller.ts",
        "src/frontend/hooks/use-extend-confirmation-controller.ts",
        "src/frontend/hooks/use-install-app-controller.ts",
        "src/frontend/hooks/use-payment-confirmation-controller.ts",
        "src/frontend/hooks/use-payment-return-status-controller.ts",
        "src/frontend/hooks/use-passkey-actions-controller.ts",
        "src/frontend/hooks/use-profile-controller.ts",
        "src/frontend/hooks/use-referral-program-controller.ts",
        "src/frontend/hooks/use-register-email-confirm-controller.ts",
        "src/frontend/hooks/use-telegram-webapp-login-controller.ts",
        "src/frontend/hooks/use-verify-email-controller.ts",
        "src/frontend/lib/chatwoot.ts",
        "src/frontend/lib/chatwoot-context-cache.ts",
        "src/frontend/lib/chatwoot-contract.ts",
        "src/frontend/lib/chatwoot-storage.ts",
        "src/frontend/lib/chatwoot-transitions.ts",
        "src/frontend/lib/chatwoot-transport.ts",
        "src/frontend/lib/install-app-transitions.ts",
        "src/frontend/lib/telegram-webapp-environment.ts",
        "src/frontend/lib/telegram-webapp-login-transitions.ts",
        "src/frontend/lib/telegram-webapp-script-loader.ts",
      ],
      thresholds: {
        statements: 60,
        branches: 45,
        functions: 70,
        lines: 60,
        "src/frontend/components/chatwoot-widget.tsx": {
          statements: 83,
          branches: 80,
          functions: 85,
          lines: 83,
        },
        "src/frontend/components/chatwoot-widget-controller.ts": {
          statements: 83,
          branches: 80,
          functions: 85,
          lines: 83,
        },
        "src/frontend/components/chatwoot-widget-state.ts": {
          statements: 83,
          branches: 80,
          functions: 85,
          lines: 83,
        },
        "src/frontend/lib/chatwoot.ts": {
          statements: 85,
          branches: 78,
          functions: 96,
          lines: 85,
        },
        "src/frontend/lib/chatwoot-context-cache.ts": {
          statements: 85,
          branches: 78,
          functions: 96,
          lines: 85,
        },
        "src/frontend/lib/chatwoot-contract.ts": {
          statements: 85,
          branches: 78,
          functions: 96,
          lines: 85,
        },
        "src/frontend/lib/chatwoot-storage.ts": {
          statements: 85,
          branches: 78,
          functions: 96,
          lines: 85,
        },
        "src/frontend/lib/chatwoot-transitions.ts": {
          statements: 85,
          branches: 78,
          functions: 96,
          lines: 85,
        },
        "src/frontend/lib/chatwoot-transport.ts": {
          statements: 85,
          branches: 78,
          functions: 96,
          lines: 85,
        },
      },
    },
  },
  resolve: {
    alias: {
      "@": path.join(projectRoot, "src"),
    },
  },
});
