#!/bin/sh
set -eu

: "${CLEAN_PAY_RELAY_TARGET_HOST:?CLEAN_PAY_RELAY_TARGET_HOST is required}"
: "${CLEAN_PAY_RELAY_TARGET_PORT:?CLEAN_PAY_RELAY_TARGET_PORT is required}"

exec nc "$CLEAN_PAY_RELAY_TARGET_HOST" "$CLEAN_PAY_RELAY_TARGET_PORT"
